# Generated by Django 2.0.1 on 2018-02-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='datafile',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
