# Generated by Django 2.0.1 on 2018-02-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_profile_datafile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='datafile',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
